# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: This is hongshushu !
name: hongshushu
email: zxh578164349@qq.com
location: DongGuang, China
company: Kayuen
company_url: #
github_url: https://github.com/zxh578164349/hongshushu

#url: http://dongchuan.github.io # the base hostname & protocol for your site
#url: http://localhost:4000
#baseurl: 
url: http://zxh578164349.github.io/hongshushu
#baseurl: /hongshushu
#url: http://hongshushu.xyz
baseurl:/hongshushu
#assets: /DONGChuan/assets

## Gem
gems:
  - jekyll-paginate
 # - jekyll-geo-pattern
  - rouge
  - kramdown
 # - jekyll-github-metadata
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

#  enable_coderay: true

# Disque
disque: zxh578164349.disqus.com
duoshuo: hongshushu


# Pagination
paginate: 6
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'
